### ISSUE TITLE
【優先度：高】名刺Transfer処理

### ISSUE THREAD

**Issue by posaune0423** [web3-BC/web3-BizCard-Frontend#10]

**Comment by bibitto** [comment]
feat/transfer-tokenで上手く名刺の送信ができなかったので要確認（11月2日現在）

**Comment by posaune0423** [comment]
@chilolin 
これってこのPRで解決してる？
https://github.com/web3-BC/web3-BizCard-Frontend/pull/26

**Comment by posaune0423** [comment]
これで解決済み
https://github.com/web3-BC/web3-BizCard-Frontend/commit/4a9ea3be760683ff73e80a27d3308e16e4f3444d
